workflows:
  android-build:
    name: Android Build Workflow
    environment:
      android:
        build_tools: "33.0.0"
        compile_sdk: 33
      java: "11"
    scripts:
      - ./gradlew clean
      - ./gradlew assembleDebug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk


